set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports MISO]
set_property IOSTANDARD LVCMOS33 [get_ports MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports CS]
set_property PACKAGE_PIN E3 [get_ports clk]

#JA1
set_property PACKAGE_PIN C17 [get_ports MOSI] 

#JA9
set_property PACKAGE_PIN F18 [get_ports CS]

#JA3
set_property PACKAGE_PIN E18 [get_ports MISO]

#JA8
set_property PACKAGE_PIN E17 [get_ports SCLK] 

set_property PACKAGE_PIN J17 [get_ports {anode[0]}]
set_property PACKAGE_PIN J18 [get_ports {anode[1]}]
set_property PACKAGE_PIN T9 [get_ports {anode[2]}]
set_property PACKAGE_PIN J14 [get_ports {anode[3]}]
set_property PACKAGE_PIN P14 [get_ports {anode[4]}]
set_property PACKAGE_PIN T14 [get_ports {anode[5]}]
set_property PACKAGE_PIN K2 [get_ports {anode[6]}]
set_property PACKAGE_PIN U13 [get_ports {anode[7]}]
set_property PACKAGE_PIN T10 [get_ports {cathode[0]}]
set_property PACKAGE_PIN R10 [get_ports {cathode[1]}]
set_property PACKAGE_PIN K16 [get_ports {cathode[2]}]
set_property PACKAGE_PIN K13 [get_ports {cathode[3]}]
set_property PACKAGE_PIN P15 [get_ports {cathode[4]}]
set_property PACKAGE_PIN T11 [get_ports {cathode[5]}]
set_property PACKAGE_PIN L18 [get_ports {cathode[6]}]
set_property PACKAGE_PIN H15 [get_ports {cathode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
